defaults:
  starting_resources:
    easy:
      credits: 2000
      research_points: 100
    normal:
      credits: 1000
      research_points: 50
    hard:
      credits: 500
      research_points: 25
  perks:
    research_efficiency: 1.0
    combat_efficiency: 1.0
    economic_efficiency: 1.0
    diplomatic_influence: 1.0

empire_archetypes:
  - name: Militant
    perks:
      research_efficiency: 0.8
      combat_efficiency: 1.5
      economic_efficiency: 0.9
      diplomatic_influence: 0.8
    color_range:
      - "#FF0000"
      - "#CC0000"
      - "#990000"
  - name: Scientific
    perks:
      research_efficiency: 1.5
      combat_efficiency: 0.8
      economic_efficiency: 1.0
      diplomatic_influence: 0.9
    color_range:
      - "#0000FF"
      - "#0000CC"
      - "#000099"
  - name: Economic
    perks:
      research_efficiency: 1.0
      combat_efficiency: 0.9
      economic_efficiency: 1.5
      diplomatic_influence: 1.0
    color_range:
      - "#FFD700"
      - "#DAA520"
      - "#B8860B"

game_settings:
  min_computer_empires: 1
  max_computer_empires: 8
  default_computer_empires: 3
  galaxy_sizes:
    small: 25
    medium: 50
    large: 100
  difficulties:
    - easy
    - normal
    - hard 