version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm test

  frontend-watch:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm run test:watch

  frontend-coverage:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm run test:coverage

  # Backend tests will be added later
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: ../docker/Dockerfile.backend
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - ENVIRONMENT=test
  #   command: pytest
