version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    command: npm test src/__tests__/index.test.ts -- --watchAll=false --verbose
    environment:
      - CI=true
      - NODE_ENV=test

  frontend-watch:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    command: npm test
    environment:
      - NODE_ENV=test

  frontend-coverage:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    command: npm test -- --coverage --watchAll=false
    environment:
      - CI=true
      - NODE_ENV=test

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    command: python -m pytest
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phaser_game_test_db
    depends_on:
      - db

  backend-verbose:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    command: python -m pytest -v
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phaser_game_test_db
    depends_on:
      - db

  backend-coverage:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    command: python -m pytest --cov=app
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phaser_game_test_db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phaser_game_test_db
