version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./config:/app/config
    environment:
      - NODE_ENV=test
    command: npm test

  frontend-watch:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./config:/app/config
    environment:
      - NODE_ENV=test
    command: npm run test:watch

  frontend-coverage:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./config:/app/config
    environment:
      - NODE_ENV=test
    command: npm run test:coverage

  # Backend tests
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend:/app
      - ./config:/config
    environment:
      - ENVIRONMENT=test
      - PYTHONPATH=/app
    command: /app/run_tests.sh

  backend-verbose:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend:/app
      - ./config:/config
    environment:
      - ENVIRONMENT=test
      - PYTHONPATH=/app
    command: /app/run_tests.sh -v

  backend-coverage:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend:/app
      - ./config:/config
    environment:
      - ENVIRONMENT=test
      - PYTHONPATH=/app
    command: /app/run_tests.sh --cov=app --cov-report=term-missing
