# Generated by Django 5.1.7 on 2025-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_type",
                    models.CharField(
                        choices=[("human", "Human"), ("computer", "Computer")],
                        default="human",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
