# Generated by Django 5.1.7 on 2025-03-21 06:15

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turn",
                    models.PositiveIntegerField(
                        default=0, help_text="Current turn number of the game"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the game was created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="When the game was last modified"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_type",
                    models.CharField(
                        choices=[("human", "Human"), ("computer", "Computer")],
                        default="human",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Empire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mineral_storage", core.fields.FixedPointField(default=0)),
                ("organic_storage", core.fields.FixedPointField(default=0)),
                ("radioactive_storage", core.fields.FixedPointField(default=0)),
                ("exotic_storage", core.fields.FixedPointField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        help_text="The game this empire belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empires",
                        to="play.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empires",
                        to="play.player",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empires",
                        to="play.race",
                    ),
                ),
            ],
        ),
    ]
