# Generated by Django 5.1.7 on 2025-03-15 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0003_empire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turn",
                    models.PositiveIntegerField(
                        default=1, help_text="Current turn number of the game"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empire",
            name="game",
            field=models.ForeignKey(
                blank=True,
                help_text="The game this empire belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empires",
                to="play.game",
            ),
        ),
    ]
