# Generated by Django 5.1.7 on 2025-03-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0004_game_empire_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empire",
            name="asteroid_belts",
        ),
        migrations.RemoveField(
            model_name="empire",
            name="planets",
        ),
        migrations.AlterField(
            model_name="game",
            name="turn",
            field=models.PositiveIntegerField(
                default=0, help_text="Current turn number of the game"
            ),
        ),
    ]
