# Generated by Django 5.1.7 on 2025-03-19 05:43

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0005_remove_empire_asteroid_belts_remove_empire_planets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empire",
            name="exotic_storage",
            field=core.fields.FixedPointField(default=0),
        ),
        migrations.AlterField(
            model_name="empire",
            name="mineral_storage",
            field=core.fields.FixedPointField(default=0),
        ),
        migrations.AlterField(
            model_name="empire",
            name="organic_storage",
            field=core.fields.FixedPointField(default=0),
        ),
        migrations.AlterField(
            model_name="empire",
            name="radioactive_storage",
            field=core.fields.FixedPointField(default=0),
        ),
    ]
