version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=spacegame.settings
      - DEBUG=1
      - POSTGRES_DB=spacegame
      - POSTGRES_USER=spacegame
      - POSTGRES_PASSWORD=spacegame
      - POSTGRES_HOST=db
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  backend-shell:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=spacegame.settings
      - DEBUG=1
      - POSTGRES_DB=spacegame
      - POSTGRES_USER=spacegame
      - POSTGRES_PASSWORD=spacegame
      - POSTGRES_HOST=db
    depends_on:
      - db
    command: /bin/bash

  backend-test:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=spacegame.test_settings
      - DEBUG=0
    command: python manage.py test

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=spacegame
      - POSTGRES_USER=spacegame
      - POSTGRES_PASSWORD=spacegame
    ports:
      - "5433:5432"

volumes:
  postgres_data: 