# Generated by Django 5.1.7 on 2025-03-15 04:50

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mineral_production",
                    core.fields.FixedPointField(
                        default=50, help_text="Base mineral production per turn"
                    ),
                ),
                (
                    "organic_production",
                    core.fields.FixedPointField(
                        default=50, help_text="Base organic production per turn"
                    ),
                ),
                (
                    "radioactive_production",
                    core.fields.FixedPointField(
                        default=50, help_text="Base radioactive production per turn"
                    ),
                ),
                (
                    "exotic_production",
                    core.fields.FixedPointField(
                        default=50, help_text="Base exotic production per turn"
                    ),
                ),
                (
                    "mineral_storage_capacity",
                    core.fields.FixedPointField(
                        default=100, help_text="Maximum mineral storage capacity"
                    ),
                ),
                (
                    "organic_storage_capacity",
                    core.fields.FixedPointField(
                        default=100, help_text="Maximum organic storage capacity"
                    ),
                ),
                (
                    "radioactive_storage_capacity",
                    core.fields.FixedPointField(
                        default=100, help_text="Maximum radioactive storage capacity"
                    ),
                ),
                (
                    "exotic_storage_capacity",
                    core.fields.FixedPointField(
                        default=100, help_text="Maximum exotic storage capacity"
                    ),
                ),
            ],
        ),
    ]
