# Generated by Django 5.1.7 on 2025-03-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celestial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Star",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "star_type",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("brown", "Brown"),
                        ],
                        help_text="The type of star",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
