# Generated by Django 5.1.7 on 2025-03-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celestial", "0003_asteroidbelt"),
    ]

    operations = [
        migrations.AddField(
            model_name="asteroidbelt",
            name="orbit",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The orbital position from the star (1 being closest)",
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="orbit",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The orbital position from the star (1 being closest)",
            ),
        ),
    ]
