# Generated by Django 5.1.7 on 2025-03-15 09:50

import celestial.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celestial", "0004_asteroidbelt_orbit_planet_orbit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asteroidbelt",
            name="orbit",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The orbital position from the star (1 being closest)",
                validators=[celestial.models.validate_positive_orbit],
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="orbit",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The orbital position from the star (1 being closest)",
                validators=[celestial.models.validate_positive_orbit],
            ),
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField(help_text="X coordinate in the galaxy")),
                ("y", models.IntegerField(help_text="Y coordinate in the galaxy")),
                (
                    "star",
                    models.OneToOneField(
                        help_text="The star at the center of this system",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system",
                        to="celestial.star",
                    ),
                ),
            ],
            options={
                "unique_together": {("x", "y")},
            },
        ),
        migrations.AddField(
            model_name="asteroidbelt",
            name="system",
            field=models.ForeignKey(
                blank=True,
                help_text="The system this asteroid belt belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asteroid_belts",
                to="celestial.system",
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="system",
            field=models.ForeignKey(
                blank=True,
                help_text="The system this planet belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planets",
                to="celestial.system",
            ),
        ),
    ]
