# Generated by Django 5.1.7 on 2025-03-15 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "celestial",
            "0005_alter_asteroidbelt_orbit_alter_planet_orbit_system_and_more",
        ),
        ("play", "0004_game_empire_game"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="system",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="system",
            name="game",
            field=models.ForeignKey(
                blank=True,
                help_text="The game this system belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="systems",
                to="play.game",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="system",
            unique_together={("game", "x", "y")},
        ),
    ]
