# Generated by Django 5.1.7 on 2025-03-19 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celestial", "0006_alter_system_unique_together_system_game_and_more"),
        ("play", "0005_remove_empire_asteroid_belts_remove_empire_planets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asteroidbelt",
            name="empire",
            field=models.ForeignKey(
                blank=True,
                help_text="The empire that owns this asteroid belt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_asteroid_belts",
                to="play.empire",
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="empire",
            field=models.ForeignKey(
                blank=True,
                help_text="The empire that owns this planet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_planets",
                to="play.empire",
            ),
        ),
    ]
