# Generated by Django 5.1.7 on 2025-03-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The unique name of the technology",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what the technology does"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESOURCES", "Resources"),
                            ("INDUSTRY", "Industry"),
                            ("SCIENCE", "Science"),
                            ("MILITARY", "Military"),
                        ],
                        help_text="The category this technology belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Technologies that must be researched before this one",
                        to="research.technology",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Technologies",
            },
        ),
    ]
