# Generated by Django 5.1.7 on 2025-03-26 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("research", "0001_initial"),
        ("research", "0002_technology_cost"),
        ("research", "0003_empiretechnology"),
    ]

    initial = True

    dependencies = [
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The unique name of the technology",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what the technology does"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESOURCES", "Resources"),
                            ("INDUSTRY", "Industry"),
                            ("SCIENCE", "Science"),
                            ("MILITARY", "Military"),
                        ],
                        help_text="The category this technology belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Technologies that must be researched before this one",
                        to="research.technology",
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        default=100, help_text="Research cost in research points"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.CreateModel(
            name="EmpireTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "research_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Number of research points invested in this technology",
                        max_digits=10,
                    ),
                ),
                (
                    "empire",
                    models.ForeignKey(
                        help_text="The empire researching the technology",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technology_research",
                        to="play.empire",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        help_text="The technology being researched",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empire_research",
                        to="research.technology",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Empire Technologies",
                "unique_together": {("technology", "empire")},
            },
        ),
    ]
