# Generated by Django 5.1.7 on 2025-03-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="cost",
            field=models.IntegerField(
                default=100, help_text="Research cost in research points"
            ),
        ),
    ]
