# Generated by Django 5.1.7 on 2025-03-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0001_initial"),
        ("research", "0002_technology_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpireTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "research_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Number of research points invested in this technology",
                        max_digits=10,
                    ),
                ),
                (
                    "empire",
                    models.ForeignKey(
                        help_text="The empire researching the technology",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technology_research",
                        to="play.empire",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        help_text="The technology being researched",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empire_research",
                        to="research.technology",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Empire Technologies",
                "unique_together": {("technology", "empire")},
            },
        ),
    ]
